apiVersion: v1
kind: Service
metadata:
 name: production-webapp
 labels:
    app: tomcatapplication
spec:
  type: LoadBalancer
  selector:
    app: tomcatapplication
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
