name: building a CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
       # pulling the code from the repository 
      - name: Code checkout
        uses: actions/checkout@v4

      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: set a short sha variable
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      # building the docker file 
      - name: docker build the image
        run: "docker build -t dhaneeshdharun/terraform:${{ env.SHORT_SHA }} . "
      # pushing the image to docker hub
      - name: docker push to docker Hub
        run: "docker push dhaneeshdharun/terraform:${{ env.SHORT_SHA }} "

      # update the deployment file with new image tag
      # install the yq took to update the yaml file
      - name: install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - name: update deployment.yaml file
        run: |
          yq -i '.spec.template.spec.containers[0].image = "dhaneeshdharun/terraform:${{ env.SHORT_SHA }}" ' manifestfiles/deployment.yaml
      
      # commit the code to code repository
      - name: commit changes
        run: /
          git config --global user.name "dhaneesh"
          git config --global user.email "dhaneeshjadhav@gmail.com"
          git add manifestfiles/deployment.yaml
          git commit -m "update the deployment file image new tag with ${{ env.SHORT_SHA }}"
          git push origin main
            