name: building a CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
       # pulling the code from the repository 
      - name: Code checkout
        uses: actions/checkout@v4

      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dhaneesh
          password: DHAjad@123

      # building the docker file 
      - name: docker build the image
        run: "docker build -t dhaneeshdharun/teraform:${{ github.sha }} . "
      
      
